version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tourie
    restart: always
    ports:
      - "6900:5432"
    environment:
      POSTGRES_USER: ypathan
      POSTGRES_PASSWORD: nokian876
      POSTGRES_DB: tourie
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local